### ISSUE TITLE
[0.9] Follow link in new window (Fl) fails in uzbl-browser

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#191] opened 2016-01-27 21:10 UTC
With the default config, `Fl` brings up the keyboard hints, but upon selecting any of the links, no new **uzbl-browser** instance pops up.

* The only way to open a link in a new window is via RMB.
* Might be related to #187
* Issue exists in **next** too

**Comment by keis** [comment] 2016-01-27 21:17
Actually looks like it's just missing a 'newwindow' tag as the last argument to follow.sh

**Comment by GSI** [comment] 2016-01-27 21:18
Note: At least for the 0.9rc no trigger seems to be set off upon finishing input. I.e. when the keyboard hint is the number **2**, upon entering `Fl2`, the text just remains there as such in the `keycmd_section`.

(Whereas with lower case `fl` it would vanish and load the according link instead.)

**Comment by GSI** [comment] 2016-01-27 21:19
@keis: Where?

This is the binding as declared in the default config:

    @cbind  Fl*  = spawn @scripts_dir/follow.sh \@< uzbl.follow.followLinks("\@follow_hint_keys", "%s", 'newwindow') >\@

**Comment by keis** [comment] 2016-01-27 21:22
```
@cbind  Fl*  = spawn @scripts_dir/follow.sh \@< uzbl.follow.followLinks("\@follow_hint_keys", "%s", 'newwindow') >\@ newwindow
```

like so, but even without that the typed stuff is still getting cleared

**Comment by GSI** [comment] 2016-01-27 22:09
Strange. Now that I did some playing around (changing `NEW_WINDOW` to `sh -c uzbl-browser ...`, then `/usr/bin/uzbl-browser ...` **and back** to the original value) it works.

However, there is a delay of up to 2 seconds once the last char (digit) of the key hint is entered.

Which shell is used by/for **spawn_sh**?

**Comment by mathstuf** [comment] 2016-01-27 22:19
@GSI: Whatever is configured for your user (we use `g_spawn`).

As for the delay, that is probably the event queue not being flushed properly. I fixed some of it with the buffered-io branch (#137), but maybe some `flush` calls need to be made when `uzbl-core` writes to its outputs?

**Comment by GSI** [comment] 2016-01-27 22:29
How are we managing changes that should go into master **and** next? Two PR's? Or will you cherry-pick?

**Comment by mathstuf** [comment] 2016-01-27 22:42
PR to `master`, merge into `next`. If it has webkit2-related things, branch off next and merge directly into next.

**Comment by keis** [comment] 2016-02-03 17:17
I believe this is fixed now

**Closed by keis** 2016-02-03 17:17 UTC
Labels: browser, master

**Comment by GSI** [comment] 2016-02-03 17:43
> I believe this is fixed now

I think so too. However, a plain call to `uzbl-browser` segfaults quite often for me, causing opening a new window to fail on that other level.

I was not able to do much debugging, but for now it seems that having an "older" uzbl-instance already open results in more segfaults (~50%) as opposed to having a fresh one or none open (0-10%) at the time of launching an instance.

**Comment by keis** [comment] 2016-02-03 18:02
If you find anything that could help reproduce that please open an issue. Some ideas on things to try

* Does it happen running uzbl-browser from the terminal or only from within a running browser
* Does it happen (more often) with certain urls?
* Does it happen running a uzbl-core without connecting to the em
* Does it happen running a uzbl-core without config and without connecting to the em
