### ISSUE TITLE
No new releases?

### ISSUE THREAD

**Issue by sandio** [uzbl/uzbl#179] opened 2016-01-12 13:46 UTC
Hi developers and contributors,

You are actively developing uzbl, I wanted to ask why there aren't any new GitHub releases (stable versions) since 2012.

I am using this excellent browser all the time on Arch Linux but we are not getting new versions maybe because there aren't any new stable releases here on GitHub.

Thanks,
Aleksandar

**Comment by keis** [comment] 2016-01-12 15:14
There is only sporadic development on uzbl at this point but I agree we really should be doing releases more often.

@mathstuf  IIRC master should more or less be ready for cutting a webkit1 release. What do you think of just cutting a release from that as it stands even if a bit shaky to at least get the past few years of patches out.

"Don't let perfect be the enemy of good"

**Comment by GSI** [comment] 2016-01-12 15:22
My two cents: Current next is working "perfectly fine" for me so far - don't know how far that's diverged differs from master.

However, somehow it should be ensured that users start with a **vanilla config**. Old (read: incorrect) config directives cause a lot of chaos.

**Comment by ballsystemlord** [comment] 2016-01-22 05:03
Dear devs, I write to you with the sad news that gentoo is dropping the uzbl browser in about 3 weeks (it's currently masked for removal).
They cite that nobody uses it, that there are few releases, and  that development is about dead.
I write to the end of trying to encourage your efforts and suggesting a way to attract more users.
I want to use uzbl but, like most internet uses, I want to browse the web safely, securely, and as anonymously as possible, NOW. WHere is most of Linux'es documentation? Online.
uzbl does not offer that out-of-the-box plug-and-play behaviour, so I've had to use firefox, lynx and other browsers for the time being. Most users probably feel the same. What's popular? KDE, GNOME, Konqueror, kmail, firfox, blender, etc. all things that have an arguably good P&P setup.
I, like most others have not found the time to reimplement noscript, privacybadger, and and the ability to control the gnash plugin into uzbl.
I think your project is fine, you just need to get better adoption.

After torturing you with such a rant I'd feel amiss it I did not volunteer.
But you may not want any of what I said, so it's up to you.
I'm going to poke my nose around uzbl, privacy badger, and the various configs online, see what I can come up with.

**Comment by keis** [comment] 2016-01-22 17:46
I'm making some effort in getting master in good shape. Any help testing and reporting issues (esp. regressions compared to earlier version) is very much appreciated. Any bigger changes or features are not likely to be added but is of course still interesting for uzbl/next

@ballsystemlord I don't think uzbl is ever going to be a pnp browser for the masses and I don't think it needs to be. Being able to tinker is more valuable than a polished product in this instance (imho).

That being said suggestions for how to improve the default config and scripts are always welcome and if you find a way of implementing privacybadger in a unix-philosophy friendly way that would be very exciting.

**Comment by rumpelsepp** [comment] 2016-01-22 18:56
@ballsystemlord Try this: https://github.com/The-Compiler/qutebrowser It is heavily inspired by uzbl.

**Comment by GSI** [comment] 2016-01-23 07:15
@ballsystemlord wrote:
> I want to use uzbl but, like most internet uses, I want to browse the web safely, securely, and as anonymously as possible

`set proxy_url http://127.0.0.1:8118#privoxy`


> Most users probably feel the same. What's popular? KDE, GNOME, Konqueror, kmail, firfox, blender, etc. all things that have an arguably good P&P setup.

The majority is usually wrong.

That "popularity" is based on marketing and bias, not brains. I mean K-whatever - seriously?


> I, like most others have not found the time to reimplement noscript, privacybadger, and and the ability to control the gnash plugin into uzbl.

* noscript: Initially, I missed that too. Then again, most web devs have no idea what "progressive enhancement" even means and create sites that fail miserably when surfed without all the JS they pull from *this* domain or *that* CDN. Allowing "only current domain + sub domains" helps a bit (and should be a feature in uzbl). I'm not sure about selective authorization like NoScript offer, though - very cumbersome on the user. (I'm aware that NS offers other protection mechanisms too, but they should be treated conceptually, not patched away with a plugin.)
* privacy badger: As a first step, use privoxy - set it up once and use it with any browser. How cool is that?
* gnash: I see no reason to use Flash these days. I'm curious about yours though.


@keis wrote:
> @ballsystemlord I don't think uzbl is ever going to be a pnp browser for the masses and I don't think it needs to be. Being able to tinker is more valuable than a polished product in this instance (imho).

uzbl's goal is to follow the UNIX philosophy and by doing so, it's probably the most flexible (and thus "feature-rich") browser out there. I mean I'm downloading YT videos, mail contents to myself, show current URLs as QR-codes --- each with one keystroke and NO additional plugins that currupt $your_currently_preferred_commercial_browser.

With uzbl you can trash stuff like Greasemonkey/Scriptish, because "it's already there". For the first time JS development doesn't have me want to tear my hair out.

Sure, we can improve on the default configs in order to include such things "for the masses". Privoxy could be added as suggested dependency and we could remove some more workload from the newcomers.


@rumpelsepp wrote:
> @ballsystemlord Try this: https://github.com/The-Compiler/qutebrowser It is heavily inspired by uzbl. 

IMHO a great example of where uzbl should avoid going :)

* Want to implement ad-blocking (which is a proxy's job)
* Tabbing is implemented (which is a WM's job)
* Overall project seems to head in a "bloaty" direction ("to bring happiness to the masses"?)

**Comment by rumpelsepp** [comment] 2016-01-23 08:06
> IMHO a great example of where uzbl should avoid going :)

It is just fine to have an example which direction you want to avoid, so you can define better what uzbl actually is and will be. :)

**Comment by ballsystemlord** [comment] 2016-02-05 20:08
> That "popularity" is based on marketing and bias, not brains. I mean K-whatever - seriously?
Yes, that's how I feel, but don't tell them that. They think they have "The next great thing." Without real numbers we'll never know and those numbers are hard to get. How many people have you met who walk up to you and say "I'm using privoxy, tor, uzbl, and linux!"

>     noscript: Initially, I missed that too. Then again, most web devs have no idea what "progressive enhancement" even means and create sites that fail miserably when surfed without all the JS they pull from this domain or that CDN. Allowing "only current domain + sub domains" helps a bit (and should be a feature in uzbl). I'm not sure about selective authorization like NoScript offer, though - very cumbersome on the user. (I'm aware that NS offers other protection mechanisms too, but they should be treated conceptually, not patched away with a plugin.)
Yes, after the first 5 websites that want to execute script I begin to wonder as well.
But controlling what JS gets execution privilages is paramount IMHO, far to many problems were caused by MSes auto execution tech of both JS and ActiveX scripts. I don't want to see linux going down the same drain. Here's another interesting article on the subject https://www.fsf.org/campaigns/freejs

> privacy badger: As a first step, use privoxy - set it up once and use it with any browser. How cool is that?
I'm using both!! I like layers of security when it comes to my browser, it's the first thing everyone seems to go after.

> gnash:  I see no reason to use Flash these days. I'm curious about yours though.
Youtube, vimeo, kickstarter, edx, various linux OSes release notes or tutorials, blender tutorials. Lots and lots of sites still, surprisingly use flash.

> It is just fine to have an example which direction you want to avoid, so you can define better what uzbl actually is and will be. :)
It's hard to see the road when all you can see is the bushes :)
Or, perhaps less metaphorically, seeing what you don't want does not point you to what you do. It just gives you a hazy idea of how things could be better.

**Comment by GSI** [comment] 2016-02-05 21:09
> Youtube, vimeo, kickstarter, edx, various linux OSes release notes or tutorials, blender tutorials. Lots and lots of sites still, surprisingly use flash.

Hey ballsystemlord,

For starters, this might help for some sites (or at least YT?):

@cbind  >y  = spawn_sh 'mpv "$UZBL_URI"'

Also check ViewTube: http://isebaro.com/viewtube
@on_event   LOAD_FINISH    js page file @scripts_dir/viewtube.min.js

(Will PR my per-site-settings so you can load this only for supported sites)

**Comment by keis** [comment] 2016-02-05 21:58
Or for youtube specfically just enable the html5 player already :)

**Comment by GSI** [comment] 2016-02-06 16:07
Last time I tried it didn't stick - had to set it again upon every visit (?)

**Comment by ballsystemlord** [comment] 2016-02-08 19:17
html5 does not always work.

> Also check ViewTube: http://isebaro.com/viewtube
I only read english and google translate does not make it clear how to use the service.
True, I could just trust that your pointing me in the right direction, but I like to know what I'm dealing with.
I'd also like to add that the script problems that I mentioned seem to have been noticed and are being addressed in other issue reports, keep up the good work :)

**Comment by keis** [comment] 2016-02-28 14:53
Released 0.9 just now. Here's to not waiting several years for the next!

**Closed by keis** 2016-02-28 14:53 UTC
