### ISSUE TITLE
[0.9] Repair form filler

### ISSUE THREAD

**Issue by GSI** [uzbl/uzbl#197] opened 2016-01-28 04:32 UTC
Upon hitting `zn` an empty (!) text file is opened in the editor.

Upon saving, a file is written (eg. data/dforms/duckduckgo.com.default).

Upon hitting `ze` again an empty file is opened which will overwrite the original one upon saving.

`zl` stays without effect.

If I remember correctly the file used to have the field names or id's pre-filled, but even then, formfiller "load" never worked for me.

**Comment by keis** [comment] 2016-01-28 08:13
Never really used the formfiller so this will take some time to look into and there seems to be multiple errors. For one the javascript dump method always returns empty (only the header, footer) for me.

**Comment by mathstuf** [comment] 2016-01-29 18:48
This did work at some point, but probably broke when I went and de-crufted the script :/ . I don't use it, but I did some light testing at the time. Maybe I dropped a hunk? Unit tests for this would be great.

**Comment by keis** [comment] 2016-01-30 16:14
The javascript was a bit broken but fixed that. The bigger issue I have right now is that the socket is closed before the response is written.

**Comment by keis** [comment] 2016-01-30 16:22
`socat` is closing its write end and then waiting 0.5 seconds (by default) before exiting. But `uzbl-core` is booting the socket off as soon as one end is closed.

Allowing half-closed sockets in core makes sense but would most likely introduce some lag in various scripts depending on being close immediatly. But at least scripts waiting for data would  have chance of getting it.

**Comment by keis** [comment] 2016-02-02 10:52
Also due to the madness that is parsing in uzbl we need to escape strings some more. This is a regression introduced by 724770. I would like to remove the unescape done by `expand_variables` but that is likely to introduce all kinds of breakage

**Comment by mathstuf** [comment] 2016-02-02 12:07
Ugh, that commit reference isn't turning into a link. What was it? And yeah, parsing is…special in uzbl.

**Comment by keis** [comment] 2016-02-02 12:15
It's when js and script was combined (724770562422e490ccc9af25be59b88331ad1c0b). With parse TRUE there is two passes of unescape.

**Comment by mathstuf** [comment] 2016-02-02 12:21
Where is the second one? In expand_variable?

**Comment by keis** [comment] 2016-02-02 12:25
yep. it's in expand_impl (variables.c) and split_quoted (commands.c)

**Comment by keis** [comment] 2016-02-02 13:05
Trying to move `set` and `even` over to using the common parser is proving to be a lot of work but I think that is what eventually needs to happen. I'm going to try moving the unescape around so that it can be done when we're not splitting the arguments.

**Closed** 2016-02-09 08:14 UTC
Labels: browser, master
